payload:
  # - DOMAIN,xx.com            域名完全匹配
  # - DOMAIN-SUFFIX,xx.com     域名后缀匹配
  # - DOMAIN-KEYWORD,xx        域名关键字匹配

  - DOMAIN-SUFFIX,115.com

  - DOMAIN-SUFFIX,dyndns.com
  - DOMAIN-SUFFIX,douyucdn.cn
  - DOMAIN-SUFFIX,douyucdn2.cn

  - DOMAIN-SUFFIX,speedtest.net
  - DOMAIN-SUFFIX,ooklaserver.net

  - DOMAIN-SUFFIX,steam-chat.com
  # - DOMAIN-SUFFIX,steamstatic.com
  # - DOMAIN-SUFFIX,cm.steampowered.com
  # - DOMAIN-SUFFIX,api.steampowered.com
