payload:
  # - DOMAIN,xx.com            域名完全匹配
  # - DOMAIN-SUFFIX,xx.com     域名后缀匹配
  # - DOMAIN-KEYWORD,xx        域名关键字匹配

  - DOMAIN,115.com

  - DOMAIN,dyndns.com
  - DOMAIN,douyucdn.cn
  - DOMAIN,douyucdn2.cn

  - DOMAIN,speedtest.net
  - DOMAIN,ooklaserver.net
