payload:
  # - DOMAIN,xx.com            域名完全匹配
  # - DOMAIN-SUFFIX,xx.com     域名后缀匹配
  # - DOMAIN-KEYWORD,xx        域名关键字匹配

  - 115.com

  - dyndns.com
  - douyucdn.cn
  - douyucdn2.cn

  - speedtest.net
  - ooklaserver.net
